### PR TITLE
Fixed minimum & exclusiveMinimum docs

### PR DESCRIPTION
**Pull request by brandonkelly**

### CODE REVIEW

**Comment by vossad01** [comment]
@brandonkelly Nice catch!  Is there a corresponding issue or pull request for this in the [spec](https://github.com/json-schema-org/json-schema-spec) repository?

**Comment by handrews** [comment]
@brandonkelly yes, thanks!  This does need to be fixed over at json-schema-org/json-schema-spec in the XML files there.  The files here are only generated from those when a new draft is published.

We should probably be more clear about that somewhere, this isn't the first time someone has submitted a fix here.

**Comment by vossad01** [comment]
@handrews 
From the README:
> This repo is currently undergoing a complete restructuring and removing of content not related to the website. It was a copy of the gh-pages branch over on the old org repo.

Is that comment still accurate?  I agree there is room for improvement, and I am trying to think of the best way to make the relationship more clear.  However, the proper approach may depend on what refactoring is in mind.

**Comment by brandonkelly** [comment]
@vossad01 looks like yes: https://github.com/json-schema-org/json-schema-spec/issues/320

@handrews just submitted a PR over at the `json-schema-org/json-schema-spec` repo: https://github.com/json-schema-org/json-schema-spec/pull/323 - sorry for missing that!

**Comment by handrews** [comment]
> Is that comment still accurate? I agree there is room for improvement, and I am trying to think of the best way to make the relationship more clear. However, the proper approach may depend on what refactoring is in mind.

I'm not really sure if @Relequestual has anything in mind.  There has not been talk of a specific major refactoring that I know of.  It should be safe to rewrite that, it's not like it would prevent us from undertaking a further refactoring! :-)

**Comment by Relequestual** [comment]
I can't really remember what I had in mind. In addition, I like the approach I've seen of moving as much as possible to markdown.

**Pull request closed without merging**
