### PR TITLE
Add Hackolade editor

### PR DESCRIPTION
**Pull request by hackolade**

### CODE REVIEW

**Comment by Relequestual** [comment]
While I can see in the news section that Hacolade is a JSON Schema editor, I don't see this mentioned in the features list.
Great looking website though! Only note is you can't click to enlarge images. I'll be checking out the application when I have time.

**Comment by hackolade** [comment]
Thanks!  I'll make the changes to the site.
While the primary purpose of the tool is data modeling for NoSQL databases, the editor is built on JSON Schema and uses JSON Schema for internal notation and persistence of the models.  The internal validator had to be extended for example to support MongoDB's BSON data types, etc...  Making the editor a plain JSON  Schema draft v4 editor is a bonus ;-)

**Comment by hackolade** [comment]
Hello Ben,  would you have some time to review our software and evaluate if it is appropriate to add it to the list of JSON Schema editors?  Your expert feedback is most welcome!  Thanks in advance!

**Comment by Relequestual** [comment]
I had a look just now. Seems you have some work to do. Basic functionality doesn't work which is a shame. I created a very basic schema. The definions weren't saved in the json schema file even though the reference was relative. 

I tried to load the json schema file back in... nothing happens.

I tried to load a few of the json schemas I've written myself... all of them threw an error, and I know they are valid. Just saying "invalid json schema file" really isn't enough.

I'm closing this now. If you can do some more work and show better support for JSON Schema, I'll reconsider, but currently I feel the support is too poor to promote your application. Sorry.

**Comment by Relequestual** [comment]
... and another thing... I'm on OSX, Command + Q doesn't quit the application. I see the shortcut is set to alt + F4... No mac user is going to like your software. Poor porting there.

**Comment by hackolade** [comment]
Thanks for the feedback.  We'll keep working at it, and will resubmit when more mature.  Best regards.

**Comment by Relequestual** [comment]
Great! I can see some people would find this a useful tool, just not our community, yet. I appreciate the effort it takes to make something like you have. Keep at it =]

**Comment by hackolade** [comment]
We're up for the challenge...  Thanks for the encouragements!  Cheers

**Pull request closed without merging**
