### PR TITLE
Added 2020-12 & 2019-09 to opis/json-schema

### PR DESCRIPTION
**Pull request by sorinsarca**

### CODE REVIEW

**Comment by Relequestual** [comment]
We are discussing this internally which may result in a policy decision.

**Comment by msarca** [comment]
If there is a problem, feel free to ask for clarifications. Thanks.

**Comment by Relequestual** [comment]
> If there is a problem, feel free to ask for clarifications. Thanks.

Will do. Thanks. We're just trying to determine our best cause of action.
If you'd like to chat informally, feel free to jump on our slack server and DM me =]

**Comment by Relequestual** [comment]
For reference, related: https://github.com/json-schema-org/JSON-Schema-Test-Suite/pull/478

**Comment by sorinsarca** [comment]
Any update on this?
We released v2.1.0 and updated the docs. Now you can [set the options](https://opis.io/json-schema/2.x/php-loader.html#parser-options) to use "vanilla" json-schema, without our added features.

**Comment by Relequestual** [comment]
I've brought this up internally again. I'll feed back resulting comments.

I appreciate the work you've done to provide feature flags.

I personally still take issue with your default use of `default.
I would go as far as to consider it harmful and misaligned with the majority of users expectations of safe useage (which is to not modify the instance data based on any keywords).

Further, `default` is presented in your docs as the only useage of default is to provide a value to modify instance data with. The feature flag disables the use of `default` as you've defined it, not completly. I find it misleading.

You've said...

> Please pay attention when using default! The value of the keyword must pass the validations!

This is at odds with the spec...

> It is RECOMMENDED that a default value be valid against the associated schema. 

It's not required.

The purpose of default is an annotation which can be used by other applications (such as form generation) to do with as they wish.

I do not feel we can update your support level here. In fact, I'm suggesting we remove it or note that it has non-compliant behaviour by default in the listing.

**Comment by sorinsarca** [comment]
Ok, thanks for your feedback, but we cannot break semver.

**Comment by Relequestual** [comment]
> Ok, thanks for your feedback, but we cannot break semver.

OK, sure, no one is asking you to. You could release a new major version.

**Comment by handrews** [comment]
> Ok, thanks for your feedback, but we cannot break semver.

Have I mentioned recently how much I detest semver for how it completely warps anything resembling a realistic progress of features?  Thank goodness OAS decided actual functionality and usage was more important than blindly adhering to a versioning spec that makes nearly everything significant a major version change that completely terrifies maintainers into paralysis.

One day maybe I'll write **Semver Considered Harmful** because the amount of harm it has done to many ecosystems is immense.

**Comment by Relequestual** [comment]
https://developer.okta.com/blog/2019/12/16/semantic-versioning

**Comment by handrews** [comment]
@Relequestual idk, the problem is less the mechanics of semantic versioning and more the fact that the tech world has collectively decided that MAJOR VERSION REVS ARE EEEEEEEEEVIL!  And just refuses to do them when they're needed.  Or does them an discards semver, which is in many ways not ideal but in my view better than just saying "well, I guess we won't do this for another three years" which is what would have happened with OAS if their marketing folks had been strict about what could and couldn't go into 3.1 vs 4.0.

Which has nothing specific to do with @sorinsarca as I have no idea what their project's constraints are.  I'm just annoyed at semver because it's one of these supposedly automatable technocratic solutions that completely disregards human nature.

**Comment by Relequestual** [comment]
By way of contrast (and my last off topic comment on this issue), remember when Firefox went semver because Chrome started releasing major version so fast?

**Pull request closed without merging**
