### PR TITLE
Point "latest" meta-schemas to draft/2019-09

### LINKED ISSUE #296: Shouldn't the file pointers be changed?
Since the publication of the new version (the current version is 2019-09), shouldn't the file pointers be changed? As it was done for the change from draft-06 to draft-07 version [by this commit](https://github.com/json-schema-org/json-schema-org.github.io/commit/0f31052fbfaee99b9a0fa128b5748e4b912e802d).

Currently the following urls point to the draft-07 version:
- [https://json-schema.org/schema#](https://json-schema.org/schema#)
- [https://json-schema.org/hyper-schema#](https://json-schema.org/hyper-schema#)
- [https://json-schema.org/links#](https://json-schema.org/links#)

Maybe it's done on purpose?

### PR DESCRIPTION
**Pull request by forresst**
fixes #296

### CODE REVIEW

**Comment by handrews** [comment]
Oops.  Yeah, I just forgot about this.

Personally, I think that for the meta-schemas, having a "latest" that will change dramatically out from under you is a horrible idea and should never be used.  It's only there for historical reasons and I'd rather remove them (but I'm guessing other people will complain?  I really wish they were gone).  The "latest" for the human-readable spec is OK (although we should change it to redirect if Jekyll can handle that, which it probably can't- have I mentioned how much I hate Jekyll this week?)

And of course the ajv test now fails, because ajv doesn't understand `2019-09`.

@gregsdennis is it possible to run Manatee.JSON in Travis somehow?

**Comment by handrews** [comment]
Ugh.  Actually this won't work at all even with Manatee.JSON because there are relative links in the new meta-schemas so we'd have to symlink *everything*.

@Relequestual @awwright in all seriousness can we just kill the "latest" meta-schemas?  They're extremely problematic.

**Comment by gregsdennis** [comment]
It's .Net standard, so you should be able to run it anywhere.  It'll need a console runner, though (or Powershell).

**Comment by handrews** [comment]
@gregsdennis yeah I have no idea whether those things are available in Travis.  @Relequestual do you know?

**Comment by notEthan** [comment]
maybe the site could 302 `/schema` to `draft/2019-09/schema` instead of symlinking? I don't know if github supports redirects but I think there is some drive to move away from github for the site.

**Comment by handrews** [comment]
@notEthan yeah I'm looking at this.  GitHub pages will only allow generating an HTML stub that will do a meta-refresh tag to redirect, which might not be acceptable for the JSON documents.  Although I would still prefer it.  It will be an improvement for the specs, which currently get checked in twice.  Why?  I have no idea, you'd think they would be symlinked... blah.

**Comment by awwright** [comment]
> in all seriousness can we just kill the "latest" meta-schemas?

Yeah why not. "latest" has some use for bookmarks and such, but this is probably more relevant to the documentation/specification. If you actually point to "latest" in a schema, you're (figuratively) asking for trouble.

**Comment by Relequestual** [comment]
Mm. As such, I revoke my approval of this change.
Thanks for your effort but will be closing in favour of #300

**Pull request closed without merging**
