### PR TITLE
Minimaizing reliance on hidden header file

### PR DESCRIPTION
**Pull request by philsturgeon**

### CODE REVIEW

**Comment by Relequestual** [comment]
@handrews Did you check what this looked like before merging? =/ Doesn't look great right now on the site.

@philsturgeon I wonder if this was complete or only partly done?

**Comment by Relequestual** [comment]
Fixed.

**Comment by handrews** [comment]
@Relequestual no, because bundle suddenly wouldn't run anything and I just table-flipped and shipped it.  Have I mentioned how much I despise using Jekyll?  HTML+CSS works and I can actually debug it.

**Comment by handrews** [comment]
And the dependencies never get messed up.

**Comment by handrews** [comment]
Next time I'll leave it for someone who doesn't scream in frustration every time they have to touch it.

**Comment by philsturgeon** [comment]
Sorry folks

**Pull request merged**
