### PR TITLE
Update @cfworker/json-schema validator library info

### PR DESCRIPTION
**Pull request by KuSh**

### CODE REVIEW

**Comment by gregsdennis** [comment]
@jdesrosiers @Julian is this mixed content thing new?  The changes have no effect on this.

**Comment by jdesrosiers** [comment]
> is this mixed content thing new?

That wasn't there when I merged website updates last week. It's referring to external links in IETF generated documents. There isn't anything we can do about this even if it was a real problem. I'd say we can merge this PR and have @Relequestual look into the Netlify settings to see if we can turn that check off or at least make it a warning or something.

**Comment by gregsdennis** [comment]
@awwright is this something that went in as part of your tooling update?

**Comment by Relequestual** [comment]
I have no idea why this is failing now when it didn't before.
I [asked if this could be turned off](https://answers.netlify.com/t/how-to-disable-mixed-content-detection-notifications/33036/13) back in 2021. The answer was no, and they weren't planning to add that option.

**Comment by KuSh** [comment]
Checks pass after merging main

**Review by Relequestual — APPROVED** [review]

**Pull request merged**
