### PR TITLE
Add new json-schema-validator library to the list of implementations

### PR DESCRIPTION
**Pull request by OptimumCode**
Hi, this is a library that I am working on and I was hoping you can add it to the list of the implementations on your website.

If the library does not meet some requirements in order to be added, please let me know. I will try my best to meet them

### CODE REVIEW

**Comment by gregsdennis** [comment]
Thanks for the contribution!

If you can, please also have a look at [Bowtie](https://bowtie.report).  It runs implementations against the official JSON Schema Test Suite.  (It's also still under development, but it's functional.)

**Comment by OptimumCode** [comment]
Thank you, @gregsdennis, I will.
I already set up the official test-suites for running them locally as a part of the CI. But I will try to integrate [Bowtie](https://bowtie.report/) as well

**Comment by OptimumCode** [comment]
> It's not necessary for this, though.

I understand that) But it looks cool to have all the statistics for all different implementations in one place

**Review by Relequestual — APPROVED** [review]
Thank you for your contribution! =]
Best of luck on completing the implementation to be fully compliant.
Please feel free to come join our slack and ask questions.
Looks like you found Bowtie. Do add your implementation there if you are able.

**Pull request merged**
