### PR TITLE
Add Vert.x Json Schema among the implementations

### PR DESCRIPTION
**Pull request by slinkydeveloper**

### CODE REVIEW

**Comment by slinkydeveloper** [comment]
@handrews can you check this one please? :smile:

**Comment by Relequestual** [comment]
Hey. Although you have specified which drafts you support in this PR, could you do the same in the project's readme, please?

Additionally, I took a quick look but I couldn't tell, are you using the official test suite?

Thanks =]

**Comment by slinkydeveloper** [comment]
> Hey. Although you have specified which drafts you support in this PR, could you do the same in the project's readme, please?

It's here: https://vertx.io/docs/vertx-json-schema/java/
Maybe I should link this page more than the github repo?

> Additionally, I took a quick look but I couldn't tell, are you using the official test suite?

Yep, here it is: https://github.com/eclipse-vertx/vertx-json-schema/tree/master/src/test/resources/tck

**Comment by Relequestual** [comment]
> 
> 
> > Hey. Although you have specified which drafts you support in this PR, could you do the same in the project's readme, please?
> 
> It's here: https://vertx.io/docs/vertx-json-schema/java/
> Maybe I should link this page more than the github repo?

I think all the links go to the github repo. I've seen too many sites go offline after a few years.

> 
> > Additionally, I took a quick look but I couldn't tell, are you using the official test suite?
> 
> Yep, here it is: https://github.com/eclipse-vertx/vertx-json-schema/tree/master/src/test/resources/tck

Ah super! I haven't touched Java in years =]

**Comment by Relequestual** [comment]
Looks like I've not always been strict on the github readme draft support notice, so in the interest of fairness...

**Comment by Relequestual** [comment]
I made a change so waiting on checks...

**Comment by slinkydeveloper** [comment]
Thanks!

**Pull request merged**
