### PR TITLE
Add FastAPI and Pydantic to JSON Schema implementations

### PR DESCRIPTION
**Pull request by tiangolo**
This PR adds [FastAPI](https://github.com/tiangolo/fastapi) and [Pydantic](https://pydantic-docs.helpmanual.io/) to the "implementations" section.

### CODE REVIEW

**Comment by Julian** [comment]
At least from a quick glance at the landing pages, these don't look like
JSON Schema implementations. Am I missing something?

**Comment by tiangolo** [comment]
Pydantic is a library to declare, serialize and validate data in Python, in most of the cases as JSON. And it generates JSON Schemas for those models, based on the Python types: https://pydantic-docs.helpmanual.io/#schema-creation

FastAPI is a web framework, powered by Pydantic. Based on OpenAPI, which uses JSON Schema for all the models. All the data definitions (models) get generated JSON Schemas, which is then used by API docs and code generation tools. That's why I added it to the section about API documentation.

**Comment by Julian** [comment]
Got it, makes sense then for the section you've got it in.

Thanks!

**Comment by tiangolo** [comment]
Awesome! Thanks! :tada:

**Pull request merged**
