### PR TITLE
Change http links to https for links to json-schema.org in documentation

### PR DESCRIPTION
**Pull request by ben-rubin**

### CODE REVIEW

**Review by Relequestual — APPROVED** [review]
Given these changes were previously also approved, I'll count this as a double approval.

**Comment by Relequestual** [comment]
Thanks for your contribution @ben-rubin! Much appreciated.

Every change counts. My first was fixing a typo on jquery docs! =D

**Comment by karenetheridge** [comment]
This PR contains invalid changes and should be reverted.

- it has been previously been asserted (in response to other people submitting nearly identical PRs) that previously-published drafts should not be changed
- the canonical URIs of the schemas used before draft2019-09 are `http`, not `https`, and should not be changed.

**Comment by karenetheridge** [comment]
never mind, I looked more closely and schema URIs themselves don't seem to be changed!
sorry about that.

**Comment by ben-rubin** [comment]
@Relequestual Thank you for allowing me the opportunity to contribute :)

**Pull request merged**
