### PR TITLE
Update Python jsonschema version support

### PR DESCRIPTION
**Pull request by bquinn**
The linked repo says "Full support for Draft 7, Draft 6, Draft 4 and Draft 3"

### CODE REVIEW

**Comment by handrews** [comment]
I'll leave this up to @Julian, as he may be waiting for 3.0.0 to get out of alpha status before changing this (FWIW, I'm in favor of advertising the support now particularly as no other Python validators are even close AFAIK)

**Comment by Julian** [comment]
That was the rationale yeah (waiting until a stable release).

But if you're both for it I don't feel strongly one way or the other, happy to merge.

**Comment by bquinn** [comment]
Thanks! I had some colleagues looking at the list and thinking that we shouldn't do our work in Python as the jsonschema implementation was out of date. So I wanted to correct their thinking :-)

**Comment by mesknock** [comment]
I think this should be reverted. As of now if you pull down the latest stable build of `jsonschema` you get 2.6.0 which only supports up to draft-04.

Furthermore, comments on this issue seem to indicate that support for draft-07 is only partially implemented: https://github.com/Julian/jsonschema/issues/400

If nothing else I believe the `notes` field should be updated to indicate that this functionality is not currently in the stable release.

**Comment by Julian** [comment]
As I mentioned I don't personally really have an opinion one way or the other here :), I would have loved for it to not have mattered and a release to have already gone out but... some day :(

If there's any consensus I am happy to do whatever, but FWIW I'm going to close that issue since essentially everything Draft 7 is in and has been for awhile so that should be fine, I just didn't remember there was a comment about it.

**Pull request merged**
