### PR TITLE
Add 404.html

### PR DESCRIPTION
**Pull request by adamvoss**
#This 404.html comes from the minima project (https://github.com/jekyll/minima).  This way we keep the JSON schema branding and navigation on 404 pages.

### CODE REVIEW

**Comment by handrews** [comment]
If we're just taking it directly from minima are there any possible licensing concerns?

**Comment by adamvoss** [comment]
I doubt it (IANAL):

 - the 404.html file is [to be] included in new project by `jekyll new` in new versions of Jekyll so it is pretty clear they intend it to be used by projects.
 - projects created with `jekyll new` do not list any sort of license restrictions on the scaffolded content (and to my knowledge never had)
    - Legally that probably doesn't mean much, but on a human level I think that supports the intention there is not an intent to enforce licensing on the scaffolded content
 - i'd rather just take steps to be compliant, but we maybe could argue these 25 lines are not a "substantial portion" of the minima software
 - if this is a violation, we are all ready in violation via the forked/modified `footer.html` in **_includes**.

If we are concerned:
 - minima is MIT licensed, which is compatible with the BSD license of this repository (I don't know the AFL).  So I believe we could add an ACKNOWLEDGEMENTS.md indicating some parts are derived from the minima theme and add its copyright/licensing status.

I have struggled with this elsewhere too.  Technically the content is under a license that requires license and copyright disclosure, but I imagine most people do not even realize that when they run `jekyll new`.  The [pages-themes](https://github.com/pages-themes) got it right by being CC0 licensed.

/cc @ashmaroli you appear to be the original author of this file.  Do you want/expect attribution for it in repositories that use it?
/cc @benbalter FYI

**Comment by ashmaroli** [comment]
@adamvoss Technically, that file has not yet been officially "released" by Jekyll or Minima and hence am not sure how much of the liberty provided by the MIT Licence applies to the file.

On a personal front, I expect no attribution of any sorts to accompany this file.

**Comment by adamvoss** [comment]
@handrews @Relequestual @awwright This, my oldest PR here, is now 2 months old.  Even if you don't want me to merge any of my own contributions, would you consider making me a member/collaborator so I can keep on top of merging the common "new implementation" or "implementation updated" PRs?

**Comment by Relequestual** [comment]
Sorry for the huge delay in looking at this and other PRs. I'm personally really swamped and have previously been responsible for making sure web stuff gets merged.
If any PRs / issues need my attention, please mention me, as this gets my attention sooner due to email filters.
Thanks
Ben

**Comment by handrews** [comment]
@adamvoss It definitely has nothing to do with the content of the PRs.  All three of us have a distracting amount of other stuff going on right now, although I think we're all starting to get back to this project based on recent emails.  Feel free to email me for more info on that or getting added as a collaborator (although I'd defer to @Relequestual for that on the web site)- my address is on the latest drafts.

**Pull request merged**
