### PR TITLE
Web UI generation: Add FormSchema

### PR DESCRIPTION
**Pull request by demsking**
Use FormSchema to generate a form using JSON Schema and Vue.js

### CODE REVIEW

**Comment by handrews** [comment]
@demsking it looks like this only works with draft-04?  It should also go on the obsolete-implementations.md page.  And at some point I need to sort the form UI section and remove the draft-04-only projects from implementations.md.  That page is supposed to be draft-06+ only.

**Comment by Anthropic** [comment]
Updated to mention support of draft 7 which is awaiting the release of [version 2.0.0](https://gitlab.com/formschema/native/merge_requests/159). Should **not** be merged until that is released unless it is put in the obsolete file.

**Comment by Relequestual** [comment]
@Anthropic any update on this?

**Comment by Anthropic** [comment]
@Relequestual doesn't look like any update in the last four months

@demsking do you have an expectation on timeline for your v2 or do you want to update the PR to put it in the obsolete-implementations.md file for now?

**Comment by Relequestual** [comment]
Given there has been no update in almost a year, I'm closing. It can be re-opened or a new PR can be created if required.

**Pull request closed without merging**
