### PR TITLE
Add networknt json-schema-validator to the Java validator list

### PR DESCRIPTION
**Pull request by stevehu**

### CODE REVIEW

**Comment by slisaasquatch** [comment]
I'm not part of this project, but I think your project already exists in the obsolete list, so you might want to remove it there.

**Comment by handrews** [comment]
I'm confused- #303 looked like it fixed both files but was closed?

**Comment by slisaasquatch** [comment]
> I'm confused- #303 looked like it fixed both files but was closed?

Sorry, I created that pull request before I realized this one existed, and this one is from the original author of the library. So I closed mine.

**Comment by handrews** [comment]
OK yeah, agree this should also be removed from implementations-obsolete.md

**Comment by handrews** [comment]
If the OP doesn't fix it we'll edit it further and merge it eventually

**Comment by stevehu** [comment]
@slisaasquatch @handrews Thanks for pointing out the obsolete list. I have removed it from the list already.

**Comment by Relequestual** [comment]
Thanks Steve! Merged!

As an aside, taking a quick look, I couldn't tell if you used the official test suite or not.
It looks like you may in some places, but also have additional tests. Is that right?

**Comment by stevehu** [comment]
@Relequestual You are right. The library is used in the light-4j framework to validate the request/response during runtime. It has a configuration to switch between pure JSON schema validation and OpenAPI 3.0 schema validation as there are some differences. I will sync with the latest official test cases again. Thanks a lot for the reminder.

**Comment by Relequestual** [comment]
@stevehu Super! At least you recognise there are differences and they matter!
Scroll back far enough in closed issues to find someone who was convinced the difference didn't matter... needless to say, I wouldn't list their implementation...

**Comment by handrews** [comment]
@stevehu fortunately in the future, OpenAPI 3.1 will use a fully compatible superset of JSON Schema draft 2019-09 (formerly known as draft-08), and present the extensions as a recognizable JSON Schema vocabulary, so eventually such special-casing won't be needed anymore.

**Comment by stevehu** [comment]
@handrews That is what I have heard. I am so glad two teams are working together :)

**Pull request merged**
