### PR TITLE
Added WebStorm and other JetBrains IDE to editors

### PR DESCRIPTION
**Pull request by prigara**
All JetBrains IDEs, including IntelliJ IDEA Community and WebStorm can validate JSON files and offer code completion and documentation using JSON Schema files.

### CODE REVIEW

**Comment by Relequestual** [comment]
Thanks.

**Comment by Relequestual** [comment]
@prigara Is anyone from JetBrains interested in how JSON Schema develops and changes?

**Comment by prigara** [comment]
Yes, sure! @zhuravlikjb has been working on JSON Schema support a lot recently.

**Comment by Relequestual** [comment]
Great! Please join the slack to engage in discussions and new spec functionality =]

**Pull request merged**
