### PR TITLE
Add JSON Guard to the PHP implementations

### PR DESCRIPTION
**Pull request by yuloh**
Thanks!

### CODE REVIEW

**Comment by Relequestual** [comment]
Sorry, I should have merged this PR first. Please can you fix your conflict? I don't have this checked out on this machine.

**Comment by yuloh** [comment]
No problem, fixed now.

**Comment by Relequestual** [comment]
Awesome! Bonus points for using the official test suite AND passing everything! if I ever write PHP again, I'll know where to turn! =D

**Comment by yuloh** [comment]
haha, thanks 😀

**Pull request merged**
