### PR TITLE
Update links to project resources

### LINKED ISSUE #2: Official IRC channel
We've got #json-schema on Freenode now. We should link to this on the website.

### PR DESCRIPTION
**Pull request by Acubed**
@Relequestual Let's do this ;)

Closes #2, #3

### CODE REVIEW

**Comment by Relequestual** [comment]
I agree.
I DO think though that we want to link to the OLD github org also. Maybe add info about it to the readme of this one?

**Comment by Relequestual** [comment]
Also, I've been convinced that we should form a sort of governance model for the project, just so we feel we're doing things right =]

**Comment by Acubed** [comment]
@Relequestual The old repo is dead, idk if there'd be a point in linking ot it. Maybe talk about it in a "History" document or something, or push an update to the repos in the old one saying "These are obsolete"

**Comment by Relequestual** [comment]
I'm very much for keeping history and contributors. Plus there's a lot of issues in there.

**Comment by Acubed** [comment]
@Relequestual Make a separate issue for it, I want to get this merged and ensure that the website can update

**Comment by Relequestual** [comment]
Valid arguemnt!

**Pull request merged**
