### PR TITLE
add syntax highlighting for json examples

### LINKED ISSUE #49: syntax highlighting
I noticed the json in the example pages was not highlight but the snippet on the homepage was so I was about to make a PR to add highlighting to the exemple too but the highlighting is done manually!

what do you think about using someing like [prismjs](http://prismjs.com/) to highlight code example ?

### PR DESCRIPTION
**Pull request by mathroc**
Syntax highlighting is done with [prism.js](http://prismjs.com/). there's different theme but I stayed with the default one. let me know if you like another one more ;)

I didn't add syntax highlighting in the spec documents. do you think I should ?

closes #49

### CODE REVIEW

**Comment by Relequestual** [comment]
Thanks for the PR. I do actually need to work out how to run the site localy!
Hum. I THINK that the spec documents are built from the specification XML, although I'm not 100% sure. @awwright ?

**Comment by mathroc** [comment]
@Relequestual this time I used jekyll with docker, if you already have docker installed, it really easy : https://github.com/jekyll/docker/wiki/Usage:-Running

**Comment by Relequestual** [comment]
Thanks @mathroc - I don't have it installed, but there's another issue which explains how to use jekyll from commandline... think it's one of these tabs....

**Comment by agebhar1** [comment]
@Relequestual if you need some help on this let me know

**Comment by Relequestual** [comment]
Thanks @agebhar1, realistically I can't spend the required time this month to look at this =/

**Comment by Relequestual** [comment]
@mathroc Could you set up a preview by allowing github pages on your forked version of the project? @agebhar1 did this at https://github.com/json-schema-org/json-schema-org.github.io/pull/69#issuecomment-273514802 and it made confirming a lot easier. I still haven't had time to chekcout your PR and look.

**Comment by mathroc** [comment]
thx @Relequestual , I had no idea I could do that, here it is : https://mathroc.github.io/json-schema-org.github.io/

**Comment by Relequestual** [comment]
Neither did I!

Don't mind me *changes theme* OK THEN.

**Pull request merged**
