### PR TITLE
Add JSONoid to implementations

### PR DESCRIPTION
**Pull request by michaelmior**
This is another schema from data tool to add to the list of implementations.

### CODE REVIEW

**Comment by handrews** [comment]
For some reason the preview deployment isn't working- this will get merged once the person who knows about that stuff is back from a conference and can take a look next week.

**Comment by michaelmior** [comment]
@handrews Thanks!

**Comment by Relequestual** [comment]
Thanks for your PR @michaelmior. It would be great if you could state your intended support in the repo readme =]

**Comment by handrews** [comment]
> Do you mean what specific features of JSON Schema? The draft version?

Should just mean draft support which you have listed.  I notice that section doesn't have consistent formatting for the draft support which is why @Relequestual might have missed it if he was looking for italics.  I'm going to merge this since the formatting problems are something we should fix.

**Review by handrews — APPROVED** [review]

**Comment by michaelmior** [comment]
@handrews Thanks!

**Comment by Relequestual** [comment]
@michaelmior Sorry. The draft version and any keywords you do not support.
I can see you specified support for 2019-09 in your PR here, but I'd love to see you specify this ALSO in your project's repo's readme.

**Comment by michaelmior** [comment]
@Relequestual Sure. I added the draft version to the README.

**Pull request merged**
