### PR TITLE
Update "latest" meta-schemas to draft-06

### PR DESCRIPTION
**Pull request by handrews**
Addresses json-schema-org/json-schema-spec#317

### CODE REVIEW

**Comment by vossad01** [comment]
Are [links](http://json-schema.org/links) and [interfaces](http://json-schema.org/interfaces) orphans or do they also need to be updated?

This is probably not the place for it, but the example schemas (geo, card, calendar, and address) also still indicate draft-04.

**Comment by handrews** [comment]
links is in the diff (and in the draft-06 directory- I literally did "cp draft-06/* .; git commit -a")

I had never even noticed interfaces.  I had to go back to the old repo to find it, and it hadn't been touched for 7 years.  I'd say file a new issue on it and give people time to explain a use case.  If no one really wants to own it I'd rather nuke it.  It's not exactly complex, and there's a large ecosystem of code generation tools out there and I doubt any of them use this.

Updating the example schemas would also be a separate issue/PR.  Feel free to file either :-), going straight to PR is fine with . me.

**Comment by vossad01** [comment]
My bad on missing 'links'.  I opened #106 regarding 'interfaces'.  Acted too quickly on that as well, re-reading your message I should have just opened a PR deleting it... time to get some more sleep :-)

**Comment by handrews** [comment]
@awwright @Relequestual @Julian this is a trivial mechanical change for a problem that is confusing people who would otherwise implement draft-06, any objections?  While I'd prefer an active approval given that this is just a bug fix of copying files, if no one objects today I'll consider @vossad01's review sufficient and merge this.

**Comment by Julian** [comment]
@handrews +1

**Comment by Relequestual** [comment]
MIght as well do something useful while compiling stuff from source -_-

**Pull request merged**
