### PR TITLE
Update ajv information

### PR DESCRIPTION
**Pull request by epoberezkin**

### CODE REVIEW

**Comment by epoberezkin** [comment]
@Relequestual - thank you! Not 100% support but close enough :)

**Comment by Relequestual** [comment]
No problem. I need to get in gear after 2020-11 release and update jsonschema.dev 😅

**Comment by epoberezkin** [comment]
Is it using Ajv?

I am not sure what else changed in 2020-11, but the current release of Ajv already supports dynamicRef/Anchor (anchor only in the root though, which seemed enough for recursiveAnchor, but probably needs to be extended for dynamicAnchor).

**Comment by Relequestual** [comment]
It does.

You'll have to check the change log... and read the spec =]

But not loads of things.

**Pull request merged**
