### PR TITLE
Added Schematron based JSON Semantic validator

### PR DESCRIPTION
**Pull request by amer-ali**
Added Schematron based JSON Semantic validator called jsontron.

### CODE REVIEW

**Comment by handrews** [comment]
I don't see the relationship to JSON Schema here?  Schematron is unrelated, AFAIK.

**Comment by amer-ali** [comment]
Thanks Henry for taking time to review it. Please take a look at below
issue that requires this type of semantic validator:
https://stackoverflow.com/questions/28629107/json-is-there-an-equivalent-of-schematron-for-json-and-json-schema-that-is-a

I posted a possible solution to that problem.

If that doesn't convince you, then I can send some more information on why
i believe it is relevant to JSON Schema.

Regards,
Amer

**Comment by amer-ali** [comment]
Thanks Greg.

I agree with your characterization that it is not implementation of  JSON
Schema per se. However, JSON Schema, though extremely useful for syntax
validation, doesn't have many facilities for co-constraint specifications.
Contrarily, in XML there is XML Schema that is equivalent to JSON Schema
and it has Schematron for co-constraint specifications. So JSON Schema
caters to one half of JSON data validation needs. I made an attempt to use
Schematron to implement the second half of JSON data validation. It is in
no way as perfect as JSON Schema but my point was to draw attention of JSON
validation community to the semantic validation void and suggest a possible
solution. I would leave it up to you folks to decide if it adds any value
for JSON community on your site.

**Comment by handrews** [comment]
@amer-ali This page (and the site containing it) are for JSON Schema its implementations.  That includes tools that use JSON Schema for purposes beyond what is covered in its specification (e.g. generating web forms from them), but does not include complementary technologies that are not, themselves, JSON Schema based.

I'm closing this as out of scope.  It has nothing to do with the quality of the idea or implementation, or its relevance for others who use JSON Schema and want additional semantic validation.  It is just that there is a very specific purpose for this page, which is to list JSON Schema implementations.

If you are interested in discussing ideas around co-constraints and JSON Schema, you will find at least a little discussion in some of the [issues tagged with "$data"](https://github.com/json-schema-org/json-schema-spec/issues?q=is%3Aissue+is%3Aopen+label%3A%24data) (the tag should probably be renamed, but we haven't because GitHub puts the tag name in the URI so renaming it would break links).

**Pull request closed without merging**
