### PR TITLE
Add doca into docs generation tools

### PR DESCRIPTION
**Pull request by tajo**
A new link.

### CODE REVIEW

**Comment by Relequestual** [comment]
Great! Have you seen the JSON Schema test suite? Would be good to try and include that in your tests to confirm compliance.

**Comment by Relequestual** [comment]
@tajo Would you mind updating your pull request to not be conflicting? I'll be able to merge then.

**Comment by Relequestual** [comment]
@handrew ahem

**Comment by handrews** [comment]
@Relequestual I need to follow up on this.  @tajo will be back and able to work on it in January.  We have a few compliance things to fix, in part because the underlying validator it's currently using doesn't handle "id" correctly, and I'd like to update it to use the now-in-spec "examples" array instead of singular "example".

Or I could re-submit the PR myself now, I suppose, and worry about the fixes later- do things listed on the site need to pass a compliance test?

**Comment by handrews** [comment]
I forgot about this and re-filed it as #67 :-P

**Pull request closed without merging**
