### PR TITLE
Added ajv to implementations

### PR DESCRIPTION
**Pull request by epoberezkin**

### CODE REVIEW

**Comment by Relequestual** [comment]
This looks like great work!

**Comment by epoberezkin** [comment]
@Relequestual Thank you for merging and the compliments :) It was on the old site, somehow got lost in the migration...

Ajv is indeed the fastest and also seems to be the most standard compliant when it comes to refs resolution (that was my main motivation to do it) and the most extensible.

@ebdrup was trying to add his [benchmark for JS validators](https://github.com/ebdrup/json-schema-benchmark) and it wasn't merged for some reason (although it was [agreed](https://github.com/json-schema/json-schema/pull/153) to merge it seemed).

Are you ok with having it here?

**Comment by Relequestual** [comment]
Hey @epoberezkin. Damn, sorry it got lost in the migration. I found it strange it wasn't already on the site given how awesome and fully featured it seems!

Adding the JS benchmaker would be awesome. I'd say it probably warrants its own section! Happy to accept a further PR if you can find the time =]

**Comment by epoberezkin** [comment]
Thank you, will do :)

**Comment by epoberezkin** [comment]
See #34

**Pull request merged**
