### PR TITLE
add a 'documentation generator' section

### PR DESCRIPTION
**Pull request by yanick**

### CODE REVIEW

**Comment by Relequestual** [comment]
Thank you for your PR.
Could you amend to indicate draft support please? =]

**Comment by Relequestual** [comment]
Also welcome to JSON Schema land. Much appreciated your perl work!

**Comment by yanick** [comment]
> Thank you for your PR.
> Could you amend to indicate draft support please? =]

Absolutely! Done.

> Also welcome to JSON Schema land. Much appreciated your perl work!

Heh. Thanks. ^.^

**Comment by yanick** [comment]
:poke:?

**Comment by Relequestual** [comment]
Wow. My apologies! Let me get on this.

**Review by Relequestual — APPROVED** [review]

**Comment by yanick** [comment]
Woot! Thanks!

**Pull request merged**
