### PR TITLE
Updates from old website

### PR DESCRIPTION
**Pull request by awwright**
Import all the updates from `json-schema/json-schema#gh-pages` since this group was created.

Before merging this, delete the gh-pages branch from https://github.com/json-schema/json-schema - @Julian can you take care of this step?

### CODE REVIEW

**Comment by Relequestual** [comment]
I'm not sure deleting the gh-pages repo is the right thing to do here.
I think we want all the changes made to the old orgs gh-pages branch... don't we?
Then, just update the contributing.md to redirect people to the new one (as well as removing the cname file)

**Comment by Relequestual** [comment]
Missed the fact that the PR was not from the json-schema org repo. Would say it's most likely fine to delete the old branch first. Thoughts @Julian ?

**Comment by Julian** [comment]
I *should* have permissions to do that, will have a look when I get to a computer

**Comment by Julian** [comment]
OK, done.

**Comment by Julian** [comment]
That appears to have 404'ed `json-schema.org` - I haven't been following very closely clearly -- are we waiting on a DNS change here?

**Comment by Acubed** [comment]
@Julian Looks good from my end now

**Comment by Acubed** [comment]
@Julian Now just merge in this PR and it should be good

**Comment by Relequestual** [comment]
Tag: Has conflicts... =/

**Comment by awwright** [comment]
When did this happen... *sigh*

**Comment by awwright** [comment]
Let's try this

Though I hope I didn't clobber any updates with the conflict resolution

**Comment by Relequestual** [comment]
I suggest waiting till I hear back from github support re the domain name fix

**Comment by Relequestual** [comment]
OK. As some of you know Github say the custom domain is now cleared. Who wants to push the merge button? =s

**Comment by awwright** [comment]
@Relequestual There's only three people who can do that

**Comment by Relequestual** [comment]
Done... Let's see what happens... =D

**Comment by Relequestual** [comment]
Looks like the update took! This means the domain is under "our control", as far as, it points to the correct github repo. Cool!

**Pull request merged**
