### PR TITLE
add Perseid Modeler

### PR DESCRIPTION
**Pull request by datensen**

### CODE REVIEW

**Review by Relequestual — CHANGES_REQUESTED** [review]
Please can you specify which versions (drafts) of JSON Schema you support? =]

**Comment by datensen** [comment]
> 

Yes, supported versions include draft 4, 6, 7, 2019-09 and 2020-12.

**Review by handrews — APPROVED** [review]
Looks like the requested changes were made, anyone see any reason not to merge?

**Review by Relequestual — APPROVED** [review]
Thanks!

**Pull request merged**
