### PR TITLE
Updating of examples / samples

### PR DESCRIPTION
**Pull request by retrosight**
With this pull request it's my intent to...

* Update the examples to Draft 7.
* Create pointers back to the spec.
* Pure markdown (no embedded HTML)
* Generally improve the illustrations.

### CODE REVIEW

**Comment by Relequestual** [comment]
Thanks for this! I'm likely to be able to review next week.

**Comment by retrosight** [comment]
Thanks for the vote of confidence, @philsturgeon. ;-) Let's hold off on merging a bit as I'm still working through all of the examples -- one still left to go: `example2.md` -- plus I'd like to invite the community over on Slack to walk through them and provide feedback.

@handrews I fixed the build fail.

**Comment by philsturgeon** [comment]
The medal will have to wait too. Fair warning I’m on vacation and was just eyeballing the diff from a hammock so somebody needs to confirm it locally, but whatever bike sheds pop up this is infinitely better than what we have now.

**Comment by retrosight** [comment]
@Relequestual Ready now for you to review and provide feedback before merging.

It looks quite wholesale on the surface yet most of the original content is still there. I tried to respect the intent of the original author(s) as much as I could.

It's going to be hard to read unless you are a diff hound.

Therefore I suggest you might want to navigate over to...

https://github.com/retrosight/json-schema-org.github.io/blob/master/learn/index.md

...and browse the complete collection as it will appear on the site.

**Comment by retrosight** [comment]
I'll also note I made some changes to `index.html` at the root domain: https://github.com/retrosight/json-schema-org.github.io/blob/master/index.md -- removal of the telescope pointers there was requested by @handrews (and I agreed with him) and I believe these changes resolve #171.

**Comment by Relequestual** [comment]
@retrosight Super thankyou for all the hard work you've clearly done on this. Sorry I wasn't able to review this when I intended. I have now started, but expect to finish today or at most end of next week.

**Comment by philsturgeon** [comment]
Merged in #221. Thank you!

**Comment by Relequestual** [comment]
Great work. I have one small fix to apply and one followup issue to raise. But honestly this is super great! Thanks again!

**Pull request closed without merging**
