### PR TITLE
Convert the software page from HTML to Markdown

### PR DESCRIPTION
**Pull request by vossad01**
Somewhat ironically (given that nearly every link on the software page has an id) there was no anchor on a heading I wished to link to.  Kramdown automatically generates anchors on headings, so making the page markdown resolved my issue and better utilizes Jekyll functionally.

I made sure to keep all the existing link `id`s or this would be have less HTML, new things can be added with markdown now if desired.  Output looks the same.  There are some structural differences (ex, initial text not in `block`) that did not affect rendering that I did not see a reason to preserve.

This also fixes a minor bug where the **Dart** link was pointing to **Clojure**.

It looked like this site [was converted from PHP/HTML to Jekyll](https://github.com/json-schema-org/json-schema-org.github.io/pull/26) which explains why this was HTML and not markdown and why I thought conversion to Markdown might be acceptable. [pandoc](http://pandoc.org/) assisted with the conversion.

### CODE REVIEW

**Comment by Relequestual** [comment]
Thanks for your effort on this @vossad01 - Looks like a neat change. I had no idea we could interlace MD and HTML through Jekyll.

Realistically, this is probably going to sit for a while before I have time to review it. If you enable github pages on your fork, I should be able to preview the changes without having to checkout locally and actually work out my build process (which I haven't done yet).

if you're able to do that, please let me know, and I'll take a look as soon as I can. =]

**Comment by vossad01** [comment]
Done: https://vossad01.github.io/json-schema-org.github.io/
I even remembered to push the relevant commits to my master branch so you wouldn't just be looking at the current website (🙃 almost for forgot this).

**Comment by Relequestual** [comment]
Super! Thanks. Hopefully I'll be able to confirm and merge this on... probably Thursday. Crazy busy right now =/

**Comment by Relequestual** [comment]
@vossad01 Thanks for doing this.
I think things will be FAR more manageable in MD than HTML.

**Pull request merged**
