### PR TITLE
added swaggest php implementation and benchmark

### PR DESCRIPTION
**Pull request by vearutop**

### CODE REVIEW

**Comment by vearutop** [comment]
Yes, it is meant to be a "Very Much Swagger" tool to handle serialization and validation. :)

**Comment by Relequestual** [comment]
Just to confirm, you do know that the swagger implementation of JSON Schema isn't the same as "pure" JSON Schema, in terms of validation?

**Comment by vearutop** [comment]
Yes I confirm, this is "pure" JSON Schema library, that is used as a base for https://github.com/swaggest/php-swagger2-schema which is a Swagger/OpenAPI tool.

Now I feel a bit sorry for misleading name.

**Comment by Relequestual** [comment]
I was pretty sure, but just wanted to make sure.
mmmm naming things is hard!

**Pull request merged**
