### PR TITLE
Change http links to https for links to json-schema.org in documentation

### PR DESCRIPTION
**Pull request by ben-rubin**

### CODE REVIEW

**Comment by Relequestual** [comment]
@ben-rubin Thank you for your well-intended PR.
Unfortunatly, we can't merge as-is, as there are a few constraints around the changes you've made.


All of the HTML and TXT files are generated from the XML files, which are not in this repo.
Old drafts are fixed and cannot be changed.
The URLs used in `$schema` and `$id` are fixed, specifically `http`, and cannot be changed.
This applies for `draft-07` and prior; the meta-schema URIs are `http`, not `https`.

In the `2019-09` draft, we [forgot](https://tools.ietf.org/html/draft-handrews-json-schema-validation-02#section-5) to update the meta-schema URI to be `https`, however in the meta-schema itself, it is `https://json-schema.org/draft/2019-09/schema`.

You're welcome to modify this PR, but a blanket search/replace isn't going to be what we need here. It's going to be a manual case by case checking job.

**Review by Relequestual — CHANGES_REQUESTED** [review]
See above comments.

**Comment by ben-rubin** [comment]
@Relequestual, thank you for the all of the info. Certainly, I will go back over it with your advice in mind.

**Review by Relequestual — APPROVED** [review]

**Comment by Relequestual** [comment]
Apologies for the INSANE long delay. This simply hasn't been on my radar. I'm trying to do better.

**Review by jdesrosiers — APPROVED** [review]

**Comment by Relequestual** [comment]
@ben-rubin if you can enable maintainers to make changes, I can push and resolve the merge conflicts, as I've rebased.

I'll give you 1 week, after which I'll push this change via another PR and close this one.

You'll still be credited for the commit =]

**Comment by Relequestual** [comment]
Please leave this PR open as GitHub are investigating a UI issue.

**Comment by ben-rubin** [comment]
Hi, my apologies for the delay. It seems that I've accidentally deleted my fork. I can recreate the pr from a new fork or just go ahead and make the change as you see fit.

**Comment by Relequestual** [comment]
> Hi, my apologies for the delay. It seems that I've accidentally deleted my fork. I can recreate the pr from a new fork or just go ahead and make the change as you see fit.

This may actually explain the UI issue I was seeing. I'll see what GitHub support say when they pick this up.

In terms of the PR, let's see who gets to it first? =]

**Comment by ben-rubin** [comment]
> 
> This may actually explain the UI issue I was seeing. I'll see what GitHub support say when they pick this up.
> 
> In terms of the PR, let's see who gets to it first? =]

New PR opened here :) https://github.com/json-schema-org/json-schema-org.github.io/pull/425

**Comment by Relequestual** [comment]
Closed in favour of #425

**Pull request closed without merging**
