### PR TITLE
Add link to Rust code generator.

### PR DESCRIPTION
**Pull request by adeschamps**

### CODE REVIEW

**Comment by Anthropic** [comment]
Hi @adeschamps will your project be updating to support greater than draft 4 soon? We are starting to put libraries that do not support the more recent standards (6+ from memory) into
`obsolete-implementations.md` instead. If you will only support up to draft 4 then the link should go in both files as it will probably be removed from this file in the not-too-distant future.

**Comment by adeschamps** [comment]
I'm not the maintainer; just an enthusiastic user. I'm inquiring about migrating here: https://github.com/Marwes/schemafy/issues/23

**Comment by membphis** [comment]
@adeschamps please rebase your PR

**Comment by handrews** [comment]
More than a month without update, closing.  If someone wants to PR this against `implementations-obsolete.md` I'd be happy to merge but not going out of my way to unravel this for something that only supports draft-04.

**Comment by handrews** [comment]
Oh wait this is a code generator not a validator, and we never sorted those out.  I'll resolve this.

**Comment by adeschamps** [comment]
Sorry about the inactivity. I've been trying to find the time to contribute to this project, but I've been busy. If you want to close this, I'll open another issue when the project eventually supports more recent drafts.

**Comment by handrews** [comment]
It looks like this meets the "doesn't actively break draft-06" qualification for code generators so I'll merge the resolved PR.

**Pull request merged**
