### PR TITLE
Adding links to meta-schemas of previous drafts

### PR DESCRIPTION
**Pull request by erosb**
Some people might still need them.

### CODE REVIEW

**Comment by handrews** [comment]
See PR #87.

@awwright @vossad01 @erosb please sort this out among yourselves :-)

**Comment by erosb** [comment]
Well I'm not going  to push it too hard if others disagree.
I just wanted to help out [http://stackoverflow.com/questions/44070559/how-to-force-fge-json-schema-validator-to-throw-an-error-on-unknown-keywords/44075531#44075531](this guy) and I needed a draft-04 meta-schema link, couldn't find any on the website, and I thought it is still useful for a lot of people.

**Comment by handrews** [comment]
@erosb it is, and if you look through #87 you'll see that preserving a link to draft-04 has more support than putting everything back.  I'm just taking a bit of a hands-off approach here as @awwright is the one who feels particularly strongly about it.  Also, Relequestual is out of touch for a few weeks so things on the web site end are moving a bit slowly right now.

**Comment by adamvoss** [comment]
@erosb  I imagine it was by accident that you pushed your library description update to this PR.  I am not sure if GitHub will make you aware of that fact when you try to create a new PR.  

You will definitely want to create a new PR for the library change.  Whether you restore original commits of this PR or just close it is up to you (#130 includes your commit and intends to supersede this PR, otherwise you would definitely want to restore the old state of this PR).

**Comment by erosb** [comment]
Weird... I actually deleted & re-created my fork for the purpose of the library update. How can that old commit of my deleted fork even exist?

**Comment by adamvoss** [comment]
When you create a PR, the commit gets stored as part of the destination repository but is not fetched by default ([they live under `refs/pull`/](https://stackoverflow.com/a/32443551/1072626)).  Even by deleting your repository the commit still exists within GitHub and is understood by this repository.

Looking at the status of things now, I am thinking you pushed your commits here before your deleted and recreated your fork which is why it shows as merging from `unknown repository`.

**Pull request closed without merging**
