### PR TITLE
Update the web site with the new draft.

### PR DESCRIPTION
**Pull request by handrews**
Tried to acknowledge that this is the fifth draft while preserving the proper IETF draft author+numbering scheme.  Also needed to change the URIs compared to what's in json-schema-spec as they were never changed from "04" before things were tagged.  Otherwise these are copied directly over.

### CODE REVIEW

**Comment by Relequestual** [comment]
Fixes https://github.com/json-schema-org/json-schema-org.github.io/issues/38

**Comment by Relequestual** [comment]
> Also needed to change the URIs compared to what's in json-schema-spec as they were never changed from "04" before things were tagged.

@awwright Should this result in a minor point release?

**Comment by Relequestual** [comment]
If there are no objections or queries over the weekend, I'll merge early next week (although may need a prompt!)

**Comment by awwright** [comment]
The meta-schema did not change with the new draft, the URI is the same
(including -04). There are no new meta-schemas. Idk if this was made
sufficiently clear, the I-D should list the URIs to use for meta-schemas. I
can't seem to find it... Which would be a problem.

We should be updating the website's links to the latest draft though, but I
have been away from my desktop all week... Feel free to update those.

I've been working on a use cases document, I'll publish that sometime too.

**Comment by Relequestual** [comment]
@awwright Confused. Metaschema wasn't mentioned. Specifically, a commit on this PR: https://github.com/json-schema-org/json-schema-org.github.io/pull/42/commits/b458a1152f11d29d0824af3c72b576ba6765f05b

**Comment by handrews** [comment]
Actually, now I'm even more confused.  @awwright The meta-schemas *should* have been changed, particularly the meta-hyper-schema.  You took out `fragmentResolution`, added `base`, and changed `methods` in such a way that the description in the meta-hyper-schema is now invalid.  Plus, in the regular meta-schema, we fixed the bug that `format` had been omitted, and several uses of `format` should have been changed from `uri` to `uriref`.

Should we perhaps rush out another draft so that we can have usable meta-schemas?  The ones at the tagged point in the spec repo do not match the current draft at all.

**Comment by handrews** [comment]
@awwright has made it clear that this isn't going to work.  I'll re-submit a new pull request with the meta-schema update removed.

**Pull request closed without merging**
