### PR TITLE
Add draft 2020-11-rc-0 preview documents for easy viewing

### PR DESCRIPTION
**Pull request by Relequestual**

### CODE REVIEW

**Comment by karenetheridge** [comment]
should https://json-schema.org/work-in-progress be updated as well? I didn't know that there was a preview up until I saw this PR.

**Comment by Relequestual** [comment]
@karenetheridge I didn't even notice that page.
This release is really not how I would have liked... I think we will have and stick to a much clearer defined process moving forward.
You can update it, but the likelihood is publication on Friday.

**Comment by karenetheridge** [comment]
publication of draft0? draft1? or the actual final document?

Would it be possible to generate some html documents and put them up somewhere for review over the weekend, please? I had not realized that things were so close to completion already and would like a chance for a final review.

**Comment by Relequestual** [comment]
rc0 went up on the 12th Nov
https://opencollective.com/json-schema/updates/json-schema-draft-2020-11-rc-0

Which is what THIS PR IS.
If you look at the filenames, they match up to these URLs

https://json-schema.org/draft/preview/2020-11-rc-0/jsonschema-core.html
and
https://json-schema.org/draft/preview/2020-11-rc-0/jsonschema-validation.html

**Pull request merged**
